### PR TITLE
Fixes #42: Move website files to root of project

### LINKED ISSUE #42: Move website files to root of project
Currently, all files are contained within a folder called "ai-cfia-ia-acia", which was generated automatically when the site was created. We must move all files to the root of the project. You might have to change the baseURL in the docusaurus.config.js file to '/'
image

### PR DESCRIPTION
**Pull request by vivalareda**
Fixes #42
tested [here](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/actions/runs/6869903414)

### CODE REVIEW

**Review by RussellJimmies — APPROVED** [review]

**Comment by rngadam** [comment]
@redat97 when you say tested, you mean it builds but how do we make sure that it deploys correctly to the website?

**Comment by vivalareda** [comment]
> @redat97 when you say tested, you mean it builds but how do we make sure that it deploys correctly to the website?

@rngadam I don't understand the question, I deployed it and the website was accessible, it wasn't at first when I configured it wrong. I deployed it not just built it

**Comment by rngadam** [comment]
> @rngadam I don't understand the question, I deployed it and the website was accessible, it wasn't at first when I configured it wrong. I deployed it not just built it

that was the answer to the question I was asking.

Question: did you deploy at the same URL or at a different URL? we should have the ability to support dev, stage, prod.

**Review by rngadam — APPROVED** [review]

**Comment by vivalareda** [comment]
> > @rngadam I don't understand the question, I deployed it and the website was accessible, it wasn't at first when I configured it wrong. I deployed it not just built it
> 
> 
> 
> that was the answer to the question I was asking.
> 
> 
> 
> Question: did you deploy at the same URL or at a different URL? we should have the ability to support dev, stage, prod.

ok cool ans yeah it was the same URL, I didn't know you could have multiple URLs i'll look into it

**Comment by rngadam** [comment]
> ok cool ans yeah it was the same URL, I didn't know you could have multiple URLs i'll look into it

ok, let's open a new issue then.

**Comment by vivalareda** [comment]
> > ok cool ans yeah it was the same URL, I didn't know you could have multiple URLs i'll look into it
> 
> ok, let's open a new issue then.

issue #51

**Pull request merged**
