### PR TITLE
Issue #34: created devcontainer, updated readme

### PR DESCRIPTION
**Pull request by RussellJimmies**
#34

### CODE REVIEW

**Review by rngadam — CHANGES_REQUESTED** [review]
change to npm

**Comment by RussellJimmies** [comment]
The yarn.lock file was a remnant of when I deployed it the first time. Reda deployed the site using npm, and now we're using npm as well for local testing.

**Review by rngadam — CHANGES_REQUESTED** [review]
at the root you have a package-lock.json without package.json. this is incorrect

in ai-cfia-ia-acia you have a package.json and package-lock.json which i think is what we're meant to use.

I believe the content of ai-cfia-ia-acia should be in the root of the repository.

**Comment by vivalareda** [comment]
Tag me next time if possible because I think we need to specify that for now the website is still deployed using yarn but yes I will change it to deploy using npm

**Comment by RussellJimmies** [comment]
I followed the step by step tutorial off the Docusaurus website for jump starting a project, and it was created automatically with that file structure. I will try adding the files at the root of the project to see if it still works.

**Comment by RussellJimmies** [comment]
I created a new Issue (#42) to address moving the files to the root

**Review by rngadam — APPROVED** [review]

**Pull request merged**
