### PR TITLE
Fixes #57: Set baseUrl using env variable

### LINKED ISSUE #51: Implement the ability to support multiple URLs for different development environment
> @rngadam I don't understand the question, I deployed it and the website was accessible, it wasn't at first when I configured it wrong. I deployed it not just built it

that was the answer to the question I was asking.

Question: did you deploy at the same URL or at a different URL? we should have the ability to support dev, stage, prod.

_Originally posted by @rngadam in https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/issues/50#issuecomment-1815359364_

As pointed out in this conversation, we don't have the ability to have a different URL for deployment test. It's necessary to have this so that we can test our deployment and changes while still having an operational website

### LINKED ISSUE #57: Set baseUrl using env variable
To allow the deployment to multiple platform, we need to be able to dynamically change the baseUrl based on the deployment

### PR DESCRIPTION
**Pull request by vivalareda**
#57 
Once the changes to the workflow are approved, I will change the workflow call to branch @main
Fixes #51 as well
Big PR sorry about that

### CODE REVIEW

**Comment by vivalareda** [comment]
Sorry about a lot of commit message says I can't squash because I have a rebase

**Review by RussellJimmies — APPROVED** [review]

**Comment by rngadam** [comment]
> Sorry about a lot of commit message says I can't squash because I have a rebase

then abort the rebase? get to the bottom of it, as 36 commits for a couple of line changes is indeed too much.

**Review by rngadam — CHANGES_REQUESTED** [review]
rebase

**Comment by vivalareda** [comment]
> > Sorry about a lot of commit message says I can't squash because I have a rebase
> 
> 
> 
> then abort the rebase? get to the bottom of it, as 36 commits for a couple of line changes is indeed too much.

I am mot familiar enough with git to think/know about that option I will look into it

**Comment by rngadam** [comment]
> I am mot familiar enough with git to think/know about that option I will look into it

get @k-allagbe to help you on this - through the teams channels.

**Comment by vivalareda** [comment]
> > I am mot familiar enough with git to think/know about that option I will look into it
> 
> get @k-allagbe to help you on this - through the teams channels.

all good I did some research since he's not here I figured it out

**Review by rngadam — APPROVED** [review]

**Pull request merged**
