### PR TITLE
Update background color and text color

### LINKED ISSUE #143: Change CSS colors
Change the colors of the links

### PR DESCRIPTION
**Pull request by ClemZ31**
This pull request updates the background color and text color in the `index.module.css` and `custom.css` files. The background color is changed to `#05486c` and the text color is changed to `#edf7f6`. This improves the overall accessibility of the application.
The choices of colors are related to CFIA Colour Palette, as well as the use of https://docusaurus.io/docs/styling-layout/#styling-your-site-with-infima
I also tried to test the website with IBM Equal Access Accessibility Checker available there : https://github.com/IBMa/equal-access

### CODE REVIEW

**Comment by RussellJimmies** [comment]
Could you provide a screenshot, please?

**Comment by ClemZ31** [comment]
In order to generate the different shades of colors chosen : https://docusaurus.io/docs/styling-layout/#styling-your-site-with-infima

Light color : #387fa3
image

Dark color : #389579
image

**Comment by RussellJimmies** [comment]
Can you post a screenshot of the updated look, please?

**Comment by ClemZ31** [comment]
@RussellJimmies 
image

**Review by RussellJimmies — APPROVED** [review]

**Pull request merged**
